.TH "/home/smitropoulos/CLionProjects/linet/include/inet_spec_packet.h" 3 "Tue Aug 20 2019" "Version 1.6" "Inet Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/smitropoulos/CLionProjects/linet/include/inet_spec_packet.h
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAGIC_PACKET_LENGTH\fP   102"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcreateMagicPacket\fP (unsigned char *magicPacket, char *physicalAddress)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAGIC_PACKET_LENGTH   102"

.SH "Function Documentation"
.PP 
.SS "int createMagicPacket (unsigned char * magicPacket, char * physicalAddress)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Inet Library from the source code\&.
