.TH "/home/smitropoulos/CLionProjects/linet/src/inet_spec_packet.c" 3 "Tue Aug 20 2019" "Version 1.6" "Inet Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/smitropoulos/CLionProjects/linet/src/inet_spec_packet.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'inet_spec_packet\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAC_ADDR_MAX\fP   6"
.br
.ti -1c
.RI "#define \fBCONVERT_BASE\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcreateMagicPacket\fP (unsigned char *magicPacket, char *mac)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONVERT_BASE   16"

.SS "#define MAC_ADDR_MAX   6"

.SH "Function Documentation"
.PP 
.SS "int createMagicPacket (unsigned char * magicPacket, char * mac)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Inet Library from the source code\&.
